<?php

namespace ThachVd\LaravelSiteControllerApi\Models;

use Illuminate\Database\Eloquent\Model;

class TlLincolnPlan extends Model
{
    protected $table = 'tllincoln_plans';
    protected $fillable = [
        'tllincoln_hotel_id',
        'tllincoln_plan_room_code',
        'tllincoln_plan_room_status',
        'tllincoln_plan_id',
        'tllincoln_plan_name',
        'tllincoln_plan_description',
        'tllincoln_plan_sell_time_from',
        'tllincoln_plan_sell_time_to',
        'tllincoln_plan_start_upload',
        'tllincoln_plan_end_upload',
        'tllincoln_plan_course_meal_breakfast',
        'tllincoln_plan_course_meal_dinner',
        'tllincoln_plan_course_meal_lunch',
        'tllincoln_plan_accept_before_days',
        'tllincoln_plan_accept_before_time',
        'tllincoln_plan_checkin_time_from',
        'tllincoln_plan_checkin_time_to',
        'tllincoln_plan_checkout_time',
        'tllincoln_plan_tax_type',
        'tllincoln_plan_image1_url',
        'tllincoln_plan_image1_caption',
        'tllincoln_plan_image1_updated_at',
        'tllincoln_plan_image2_url',
        'tllincoln_plan_image2_caption',
        'tllincoln_plan_image2_updated_at',
        'tllincoln_plan_image3_url',
        'tllincoln_plan_image3_caption',
        'tllincoln_plan_image3_updated_at',
        'tllincoln_plan_limited_quantity',
        'tllincoln_plan_cancellation_policy',
        'tllincoln_plan_min_person',
        'tllincoln_plan_max_person',
        'tllincoln_plan_fee_child_high_accept',
        'tllincoln_plan_fee_child_high_count',
        'tllincoln_plan_fee_child_high_value',
        'tllincoln_plan_fee_child_high_unit_option',
        'tllincoln_plan_fee_child_low_accept',
        'tllincoln_plan_fee_child_low_count',
        'tllincoln_plan_fee_child_low_value',
        'tllincoln_plan_fee_child_low_unit_option',
        'tllincoln_plan_fee_child_meal_sleep_accept',
        'tllincoln_plan_fee_child_meal_sleep_count',
        'tllincoln_plan_fee_child_meal_sleep_value',
        'tllincoln_plan_fee_child_meal_sleep_option',
        'tllincoln_plan_fee_child_meal_accept',
        'tllincoln_plan_fee_child_meal_count',
        'tllincoln_plan_fee_child_meal_value',
        'tllincoln_plan_fee_child_meal_option',
        'tllincoln_plan_fee_child_sleep_accept',
        'tllincoln_plan_fee_child_sleep_count',
        'tllincoln_plan_fee_child_sleep_value',
        'tllincoln_plan_fee_child_sleep_option',
        'tllincoln_plan_fee_child_none_accept',
        'tllincoln_plan_fee_child_none_count',
        'tllincoln_plan_fee_child_none_value',
        'tllincoln_plan_fee_child_none_option',
        'tllincoln_plan_night_stay_from',
        'tllincoln_plan_night_stay_to',
        'tllincoln_plan_update_type',
        'tllincoln_plan_updated_at',
        'tllincoln_plan_use_type',
        'tllincoln_plan_cancel_id',
        'tllincoln_plan_image1_add_url',
        'tllincoln_plan_image1_add_caption',
        'tllincoln_plan_image1_add_updated_at',
        'tllincoln_plan_image2_add_url',
        'tllincoln_plan_image2_add_caption',
        'tllincoln_plan_image2_add_updated_at',
        'tllincoln_plan_image3_add_url',
        'tllincoln_plan_image3_add_caption',
        'tllincoln_plan_image3_add_updated_at',
        'tllincoln_plan_image4_add_url',
        'tllincoln_plan_image4_add_caption',
        'tllincoln_plan_image4_add_updated_at',
        'tllincoln_plan_image5_add_url',
        'tllincoln_plan_image5_add_caption',
        'tllincoln_plan_image5_add_updated_at',
        'tllincoln_plan_image6_add_url',
        'tllincoln_plan_image6_add_caption',
        'tllincoln_plan_image6_add_updated_at',
        'tllincoln_plan_image7_add_url',
        'tllincoln_plan_image7_add_caption',
        'tllincoln_plan_image7_add_updated_at',
        'tllincoln_plan_image8_add_url',
        'tllincoln_plan_image8_add_caption',
        'tllincoln_plan_image8_add_updated_at',
        'tllincoln_plan_image9_add_url',
        'tllincoln_plan_image9_add_caption',
        'tllincoln_plan_image9_add_updated_at',
        'tllincoln_plan_image10_add_url',
        'tllincoln_plan_image10_add_caption',
        'tllincoln_plan_image10_add_updated_at',
        'tllincoln_plan_image11_add_url',
        'tllincoln_plan_image11_add_caption',
        'tllincoln_plan_image11_add_updated_at',
        'tllincoln_plan_image12_add_url',
        'tllincoln_plan_image12_add_caption',
        'tllincoln_plan_image12_add_updated_at',
        'tllincoln_plan_image13_add_url',
        'tllincoln_plan_image13_add_caption',
        'tllincoln_plan_image13_add_updated_at',
        'tllincoln_plan_image14_add_url',
        'tllincoln_plan_image14_add_caption',
        'tllincoln_plan_image14_add_updated_at',
        'tllincoln_plan_image15_add_url',
        'tllincoln_plan_image15_add_caption',
        'tllincoln_plan_image15_add_updated_at',
        'tllincoln_plan_image16_add_url',
        'tllincoln_plan_image16_add_caption',
        'tllincoln_plan_image16_add_updated_at',
        'tllincoln_plan_image17_add_url',
        'tllincoln_plan_image17_add_caption',
        'tllincoln_plan_image17_add_updated_at',
        'tllincoln_plan_image18_add_url',
        'tllincoln_plan_image18_add_caption',
        'tllincoln_plan_image18_add_updated_at',
    ];
    const DELETE_FLAG = 3;

    const TLLINCOLN_COURSE_MEAL = [
        'NO_MEALS'   => 0,
        'HAVE_MEALS' => 1,
    ];

    const TLLINCOLN_FEE_CHILD_ACCEPT = [
        'NO_ACCEPT' => 0,
        'ACCEPT'    => 1,
    ];

    const CSV_ATTRIBUTE = [
        'TLLINCOLN_HOTEL_ID'               => 0,
        'ROOM_CODE'                        => 1,
        'ROOM_STATUS'                      => 2,
        'PLAN_ID'                          => 3,
        'PLAN_NAME'                        => 4,
        'PLAN_DESCRIPTION'                 => 5,
        'PLAN_SELL_TIME_FROM'              => 6,
        'PLAN_SELL_TIME_TO'                => 7,
        'PLAN_START_UPLOAD'                => 8,
        'PLAN_END_UPLOAD'                  => 9,
        'PLAN_COURSE_MEAL_BREAKFAST'       => 10,
        'PLAN_COURSE_MEAL_DINNER'          => 11,
        'PLAN_COURSE_MEAL_LUNCH'           => 12,
        'PLAN_ACCEPT_BEFORE_DAYS'          => 13,
        'PLAN_ACCEPT_BEFORE_TIME'          => 14,
        'PLAN_CHECKIN_TIME_FROM'           => 15,
        'PLAN_CHECKIN_TIME_TO'             => 16,
        'PLAN_CHECKOUT_TIME'               => 17,
        'PLAN_TAX_TYPE'                    => 18,
        'PLAN_LIMITED_QUANTITY'            => 28,
        'PLAN_CANCELLATION_POLICY'         => 29,
        'PLAN_MIN_PERSON'                  => 30,
        'PLAN_MAX_PERSON'                  => 31,
        'PLAN_FEE_CHILD_HIGH_ACCEPT'       => 32,
        'PLAN_FEE_CHILD_HIGH_COUNT'        => 33,
        'PLAN_FEE_CHILD_HIGH_VALUE'        => 34,
        'PLAN_FEE_CHILD_HIGH_UNIT_OPTION'  => 35,
        'PLAN_FEE_CHILD_LOW_ACCEPT'        => 36,
        'PLAN_FEE_CHILD_LOW_COUNT'         => 37,
        'PLAN_FEE_CHILD_LOW_VALUE'         => 38,
        'PLAN_FEE_CHILD_LOW_UNIT_OPTION'   => 39,
        'PLAN_FEE_CHILD_MEAL_SLEEP_ACCEPT' => 40,
        'PLAN_FEE_CHILD_MEAL_SLEEP_COUNT'  => 41,
        'PLAN_FEE_CHILD_MEAL_SLEEP_VALUE'  => 42,
        'PLAN_FEE_CHILD_MEAL_SLEEP_OPTION' => 43,
        'PLAN_FEE_CHILD_MEAL_ACCEPT'       => 44,
        'PLAN_FEE_CHILD_MEAL_COUNT'        => 45,
        'PLAN_FEE_CHILD_MEAL_VALUE'        => 46,
        'PLAN_FEE_CHILD_MEAL_OPTION'       => 47,
        'PLAN_FEE_CHILD_SLEEP_ACCEPT'      => 48,
        'PLAN_FEE_CHILD_SLEEP_COUNT'       => 49,
        'PLAN_FEE_CHILD_SLEEP_VALUE'       => 50,
        'PLAN_FEE_CHILD_SLEEP_OPTION'      => 51,
        'PLAN_FEE_CHILD_NONE_ACCEPT'       => 52,
        'PLAN_FEE_CHILD_NONE_COUNT'        => 53,
        'PLAN_FEE_CHILD_NONE_VALUE'        => 54,
        'PLAN_FEE_CHILD_NONE_OPTION'       => 55,
        'PLAN_NIGHT_STAY_FROM'             => 56,
        'PLAN_NIGHT_STAY_TO'               => 57,
        'PLAN_UPDATED_AT'                  => 58,
        'PLAN_USE_TYPE'                    => 59,
    ];
    const COURSE_MEAL = [
        'TWO_MEALS'      => 1,
        'BREAKFAST_ONLY' => 2,
        'DINNER_ONLY'    => 3,
        'NO_MEALS'       => 4,
    ];
}
