<?php

namespace ThachVd\LaravelSiteControllerApi\Models;

use Illuminate\Database\Eloquent\Model;

class TlLincolnRoomType extends Model
{
    protected $table = 'tllincoln_roomtypes';
    protected $fillable = [
        'tllincoln_hotel_id',
        'tllincoln_roomtype_status',
        'tllincoln_roomtype_code',
        'tllincoln_roomtype_name',
        'tllincoln_roomtype_description',
        'tllincoln_roomtype_min_person',
        'tllincoln_roomtype_max_person',
        'tllincoln_roomtype_type',
        'tllincoln_roomtype_smoking',
        'tllincoln_roomtype_no_smoking',
        'tllincoln_roomtype_bus',
        'tllincoln_roomtype_toilet',
        'tllincoln_roomtype_internet',
        'tllincoln_roomtype_image_url',
        'tllincoln_roomtype_image_caption',
        'tllincoln_roomtype_image_updated_at',
        'tllincoln_roomtype_flag',
        'tllincoln_roomtype_update_type',
        'tllincoln_roomtype_code_others',
        'tllincoln_roomtype_updated_at',
        'tllincoln_roomtype_image1_url',
        'tllincoln_roomtype_image1_caption',
        'tllincoln_roomtype_image1_updated_at',
        'tllincoln_roomtype_image2_url',
        'tllincoln_roomtype_image2_caption',
        'tllincoln_roomtype_image2_updated_at',
        'tllincoln_roomtype_image3_url',
        'tllincoln_roomtype_image3_caption',
        'tllincoln_roomtype_image3_updated_at',
        'tllincoln_roomtype_image4_url',
        'tllincoln_roomtype_image4_caption',
        'tllincoln_roomtype_image4_updated_at',
        'tllincoln_roomtype_image5_url',
        'tllincoln_roomtype_image5_caption',
        'tllincoln_roomtype_image5_updated_at',
        'tllincoln_roomtype_image6_url',
        'tllincoln_roomtype_image6_caption',
        'tllincoln_roomtype_image6_updated_at',
        'tllincoln_roomtype_image7_url',
        'tllincoln_roomtype_image7_caption',
        'tllincoln_roomtype_image7_updated_at',
        'tllincoln_roomtype_image8_url',
        'tllincoln_roomtype_image8_caption',
        'tllincoln_roomtype_image8_updated_at',
        'tllincoln_roomtype_image9_url',
        'tllincoln_roomtype_image9_caption',
        'tllincoln_roomtype_image9_updated_at',
        'tllincoln_roomtype_image10_url',
        'tllincoln_roomtype_image10_caption',
        'tllincoln_roomtype_image10_updated_at',
        'tllincoln_roomtype_image11_url',
        'tllincoln_roomtype_image11_caption',
        'tllincoln_roomtype_image11_updated_at',
        'tllincoln_roomtype_image12_url',
        'tllincoln_roomtype_image12_caption',
        'tllincoln_roomtype_image12_updated_at',
        'tllincoln_roomtype_image13_url',
        'tllincoln_roomtype_image13_caption',
        'tllincoln_roomtype_image13_updated_at',
        'tllincoln_roomtype_image14_url',
        'tllincoln_roomtype_image14_caption',
        'tllincoln_roomtype_image14_updated_at',
        'tllincoln_roomtype_image15_url',
        'tllincoln_roomtype_image15_caption',
        'tllincoln_roomtype_image15_updated_at',
        'tllincoln_roomtype_image16_url',
        'tllincoln_roomtype_image16_caption',
        'tllincoln_roomtype_image16_updated_at',
        'tllincoln_roomtype_image17_url',
        'tllincoln_roomtype_image17_caption',
        'tllincoln_roomtype_image17_updated_at',
        'tllincoln_roomtype_image18_url',
        'tllincoln_roomtype_image18_caption',
        'tllincoln_roomtype_image18_updated_at',
        'tllincoln_roomtype_image19_url',
        'tllincoln_roomtype_image19_caption',
        'tllincoln_roomtype_image19_updated_at',
    ];
    const DELETE_FLAG = 3;

    const FLAG = [
        'ONLY_SELL_TLLINCOLN' => 0,
        'SELL_BOTH'           => 1,
    ];

    const CSV_ATTRIBUTE = [
        'TLLINCOLN_HOTEL_ID' => 0,
        'STATUS'             => 1,
        'CODE'               => 2,
        'NAME'               => 3,
        'DESCRIPTION'        => 4,
        'MIN_PERSON'         => 5,
        'MAX_PERSON'         => 6,
        'TYPE'               => 7,
        'SMOKING'            => 8,
        'NO_SMOKING'         => 9,
        'BUS'                => 10,
        'TOILET'             => 11,
        'INTERNET'           => 12,
        'IMAGE_URL'          => 13,
        'IMAGE_CAPTION'      => 14,
        'IMAGE_UPDATED_AT'   => 15,
        'FLAG'               => 16,
        'CODE_OTHERS'        => 17,
        'UPDATED_AT'         => 18,
        'IMAGE1_URL'         => 19,
        'IMAGE1_CAPTION'     => 20,
        'IMAGE1_UPDATED_AT'  => 21,
        'IMAGE2_URL'         => 22,
        'IMAGE2_CAPTION'     => 23,
        'IMAGE2_UPDATED_AT'  => 24,
        'IMAGE3_URL'         => 25,
        'IMAGE3_CAPTION'     => 26,
        'IMAGE3_UPDATED_AT'  => 27,
        'IMAGE4_URL'         => 28,
        'IMAGE4_CAPTION'     => 29,
        'IMAGE4_UPDATED_AT'  => 30,
        'IMAGE5_URL'         => 31,
        'IMAGE5_CAPTION'     => 32,
        'IMAGE5_UPDATED_AT'  => 33,
        'IMAGE6_URL'         => 34,
        'IMAGE6_CAPTION'     => 35,
        'IMAGE6_UPDATED_AT'  => 36,
        'IMAGE7_URL'         => 37,
        'IMAGE7_CAPTION'     => 38,
        'IMAGE7_UPDATED_AT'  => 39,
        'IMAGE8_URL'         => 40,
        'IMAGE8_CAPTION'     => 41,
        'IMAGE8_UPDATED_AT'  => 42,
        'IMAGE9_URL'         => 43,
        'IMAGE9_CAPTION'     => 44,
        'IMAGE9_UPDATED_AT'  => 45,
        'IMAGE10_URL'        => 46,
        'IMAGE10_CAPTION'    => 47,
        'IMAGE10_UPDATED_AT' => 48,
        'IMAGE11_URL'        => 49,
        'IMAGE11_CAPTION'    => 50,
        'IMAGE11_UPDATED_AT' => 51,
        'IMAGE12_URL'        => 52,
        'IMAGE12_CAPTION'    => 53,
        'IMAGE12_UPDATED_AT' => 54,
        'IMAGE13_URL'        => 55,
        'IMAGE13_CAPTION'    => 56,
        'IMAGE13_UPDATED_AT' => 57,
        'IMAGE14_URL'        => 58,
        'IMAGE14_CAPTION'    => 59,
        'IMAGE14_UPDATED_AT' => 60,
        'IMAGE15_URL'        => 61,
        'IMAGE15_CAPTION'    => 62,
        'IMAGE15_UPDATED_AT' => 63,
        'IMAGE16_URL'        => 64,
        'IMAGE16_CAPTION'    => 65,
        'IMAGE16_UPDATED_AT' => 66,
        'IMAGE17_URL'        => 67,
        'IMAGE17_CAPTION'    => 68,
        'IMAGE17_UPDATED_AT' => 69,
        'IMAGE18_URL'        => 70,
        'IMAGE18_CAPTION'    => 71,
        'IMAGE18_UPDATED_AT' => 72,
        'IMAGE19_URL'        => 73,
        'IMAGE19_CAPTION'    => 74,
        'IMAGE19_UPDATED_AT' => 75,
    ];

    const CSV_ATTRIBUTE_DIFF = [
        'TLLINCOLN_HOTEL_ID' => 0,
        'STATUS'             => 1,
        'CODE'               => 2,
        'NAME'               => 3,
        'DESCRIPTION'        => 4,
        'MIN_PERSON'         => 5,
        'MAX_PERSON'         => 6,
        'TYPE'               => 7,
        'SMOKING'            => 8,
        'NO_SMOKING'         => 9,
        'BUS'                => 10,
        'TOILET'             => 11,
        'INTERNET'           => 12,
        'IMAGE_URL'          => 13,
        'IMAGE_CAPTION'      => 14,
        'IMAGE_UPDATED_AT'   => 15,
        'FLAG'               => 16,
        'UPDATE_TYPE'        => 17,
        'CODE_OTHERS'        => 18,
        'UPDATED_AT'         => 19,
        'IMAGE1_URL'         => 20,
        'IMAGE1_CAPTION'     => 21,
        'IMAGE1_UPDATED_AT'  => 22,
        'IMAGE2_URL'         => 23,
        'IMAGE2_CAPTION'     => 24,
        'IMAGE2_UPDATED_AT'  => 25,
        'IMAGE3_URL'         => 26,
        'IMAGE3_CAPTION'     => 27,
        'IMAGE3_UPDATED_AT'  => 28,
        'IMAGE4_URL'         => 29,
        'IMAGE4_CAPTION'     => 30,
        'IMAGE4_UPDATED_AT'  => 31,
        'IMAGE5_URL'         => 32,
        'IMAGE5_CAPTION'     => 33,
        'IMAGE5_UPDATED_AT'  => 34,
        'IMAGE6_URL'         => 35,
        'IMAGE6_CAPTION'     => 36,
        'IMAGE6_UPDATED_AT'  => 37,
        'IMAGE7_URL'         => 38,
        'IMAGE7_CAPTION'     => 39,
        'IMAGE7_UPDATED_AT'  => 40,
        'IMAGE8_URL'         => 41,
        'IMAGE8_CAPTION'     => 42,
        'IMAGE8_UPDATED_AT'  => 43,
        'IMAGE9_URL'         => 44,
        'IMAGE9_CAPTION'     => 45,
        'IMAGE9_UPDATED_AT'  => 46,
        'IMAGE10_URL'        => 47,
        'IMAGE10_CAPTION'    => 48,
        'IMAGE10_UPDATED_AT' => 49,
        'IMAGE11_URL'        => 50,
        'IMAGE11_CAPTION'    => 51,
        'IMAGE11_UPDATED_AT' => 52,
        'IMAGE12_URL'        => 53,
        'IMAGE12_CAPTION'    => 54,
        'IMAGE12_UPDATED_AT' => 55,
        'IMAGE13_URL'        => 56,
        'IMAGE13_CAPTION'    => 57,
        'IMAGE13_UPDATED_AT' => 58,
        'IMAGE14_URL'        => 59,
        'IMAGE14_CAPTION'    => 60,
        'IMAGE14_UPDATED_AT' => 61,
        'IMAGE15_URL'        => 62,
        'IMAGE15_CAPTION'    => 63,
        'IMAGE15_UPDATED_AT' => 64,
        'IMAGE16_URL'        => 65,
        'IMAGE16_CAPTION'    => 66,
        'IMAGE16_UPDATED_AT' => 67,
        'IMAGE17_URL'        => 68,
        'IMAGE17_CAPTION'    => 69,
        'IMAGE17_UPDATED_AT' => 70,
        'IMAGE18_URL'        => 71,
        'IMAGE18_CAPTION'    => 72,
        'IMAGE18_UPDATED_AT' => 73,
        'IMAGE19_URL'        => 74,
        'IMAGE19_CAPTION'    => 75,
        'IMAGE19_UPDATED_AT' => 76,
    ];
}
